### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/currency#1]
Translation issues
Since a few commits those messages appear in the client console:

2020-03-19 21:42:44: ERROR[Main]: Ignoring empty translation for "@1 Minegeld cent coin"
@BuckarooBanzay

**Comment by BuckarooBanzay** [comment]
I can't reproduce that, what minetest version? (i'm on 5.5.0-dev `bf3acbf38`)

**Comment by wsor4035** [comment]
> I can't reproduce that, what minetest version? (i'm on 5.5.0-dev `bf3acbf38`)

i dunno, its your original issue that was ported over

**Comment by BuckarooBanzay** [comment]
> i dunno, its your original issue that was ported over

Heh, in that case: closing :D

**Comment by OgelGames** [comment]
I think it's these:
https://github.com/mt-mods/currency/blob/f74ee653b8f8c60ea4f78e7dd827dcc568649dee/locale/currency.ru.tr#L18
https://github.com/mt-mods/currency/blob/f74ee653b8f8c60ea4f78e7dd827dcc568649dee/locale/currency.ms.tr#L18
